### ISSUE TITLE
Add Property "shared"

### ISSUE THREAD

**Issue by a-marcel** [deangiberson/docker_aws_dynamodb_local#2]
Hello,

it is possible to pass the option "-sharedDb" at start into the docker ?

Thanks
Marcel

**Comment by deangiberson** [comment]
I'm not a fan of making that change. Too many people are already using the original version that this may be a breaking change. I'll make a new repo with the sharedDb option.

**Comment by deangiberson** [comment]
Please look at https://hub.docker.com/r/deangiberson/docker_aws_dynamodb_local_shareddb/
